# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-10 12:51

import django.db.models.deletion
from django.db import migrations, models


# The replaced chain's 0003 created MagentoExporterLog; the model was later removed from the code
# without a DeleteModel migration, so it is intentionally absent here (schema == current models).
class Migration(migrations.Migration):
    replaces = [
        ("django_pim_export_to_magento_api", "0001_initial"),
        ("django_pim_export_to_magento_api", "0002_channel_create_option_in_magento"),
        ("django_pim_export_to_magento_api", "0003_magentoexporterlog"),
        ("django_pim_export_to_magento_api", "0004_exportinmagento_product_and_more"),
        ("django_pim_export_to_magento_api", "0005_magentostore_pictures"),
        ("django_pim_export_to_magento_api", "0006_alter_magentostore_unique_together_and_more"),
        ("django_pim_export_to_magento_api", "0007_exportinmagento_failed_message"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
        ("django_regional", "0002_reset_pk_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=64)),
                (
                    "create_option_in_magento",
                    models.BooleanField(
                        default=True, help_text="Determines whether attribute options should be created in Magento"
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True, related_name="magento_export_features_channel", to="django_pim.feature"
                    ),
                ),
                (
                    "product_create_features",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Choose wich features will be passed to magento with product create",
                        related_name="magento_export_product_features_channel",
                        to="django_pim.feature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MagentoStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("store_view_code", models.CharField(blank=True, max_length=256, null=True)),
                ("magento_pk", models.PositiveIntegerField(blank=True, help_text="website_id from magento", null=True)),
                ("default", models.BooleanField(default=False, help_text="Default storeview for whole magento")),
                (
                    "pictures",
                    models.BooleanField(
                        default=False,
                        help_text="Choose only one per channel, because magento can't handle pictures per storeview",
                    ),
                ),
                ("products", models.BooleanField(default=False)),
                ("prices", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magento_stores",
                        to="django_pim_export_to_magento_api.channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
                (
                    "language",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.language"),
                ),
            ],
            options={
                "unique_together": {("channel", "store_view_code")},
            },
        ),
        migrations.CreateModel(
            name="ExportInMagento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "export_status",
                    models.IntegerField(choices=[(0, "success"), (1, "failed"), (2, "pending"), (3, "skip")]),
                ),
                ("export_type", models.IntegerField(choices=[(0, "product_pictures"), (1, "product")])),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("failed_message", models.TextField(blank=True, null=True, verbose_name="Failed Message")),
                (
                    "content_exported",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports_in_magento",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports_in_magento",
                        to="django_pim_export_to_magento_api.magentostore",
                        verbose_name="store",
                    ),
                ),
            ],
        ),
    ]
