# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-08-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pim_export_to_magento_api", "0001_squashed_0007_exportinmagento_failed_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="magentostore",
            name="check_prices",
            field=models.BooleanField(
                default=False,
                help_text="During product export skip this store view (and drop its website) when the product has no price in this currency and country",
            ),
        ),
    ]
